//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarvelApp.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MarvelApp.I18N.AppTexts", typeof(AppTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string EmptyDate {
            get {
                return ResourceManager.GetString("EmptyDate", resourceCulture);
            }
        }
        
        internal static string EmptyDescription {
            get {
                return ResourceManager.GetString("EmptyDescription", resourceCulture);
            }
        }
        
        internal static string Ok_Button_Label {
            get {
                return ResourceManager.GetString("Ok_Button_Label", resourceCulture);
            }
        }
        
        internal static string Cancel_Button_Label {
            get {
                return ResourceManager.GetString("Cancel_Button_Label", resourceCulture);
            }
        }
        
        internal static string HandleErrorDialog_Title {
            get {
                return ResourceManager.GetString("HandleErrorDialog_Title", resourceCulture);
            }
        }
        
        internal static string HandleErrorDialog_Message {
            get {
                return ResourceManager.GetString("HandleErrorDialog_Message", resourceCulture);
            }
        }
        
        internal static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        internal static string HomePage_ComicsList_Title {
            get {
                return ResourceManager.GetString("HomePage_ComicsList_Title", resourceCulture);
            }
        }
        
        internal static string HomePage_SeriesList_Title {
            get {
                return ResourceManager.GetString("HomePage_SeriesList_Title", resourceCulture);
            }
        }
        
        internal static string SearchPage_Title {
            get {
                return ResourceManager.GetString("SearchPage_Title", resourceCulture);
            }
        }
        
        internal static string SearchPage_SearchEntry_Placeholder {
            get {
                return ResourceManager.GetString("SearchPage_SearchEntry_Placeholder", resourceCulture);
            }
        }
        
        internal static string SearchPage_Empty_Label {
            get {
                return ResourceManager.GetString("SearchPage_Empty_Label", resourceCulture);
            }
        }
        
        internal static string SearchPage_SearchType_Label {
            get {
                return ResourceManager.GetString("SearchPage_SearchType_Label", resourceCulture);
            }
        }
        
        internal static string SearchPage_Comics_Button {
            get {
                return ResourceManager.GetString("SearchPage_Comics_Button", resourceCulture);
            }
        }
        
        internal static string SearchPage_Series_Button {
            get {
                return ResourceManager.GetString("SearchPage_Series_Button", resourceCulture);
            }
        }
        
        internal static string ItemDetailPage_Title_Label {
            get {
                return ResourceManager.GetString("ItemDetailPage_Title_Label", resourceCulture);
            }
        }
        
        internal static string ItemDetailPage_Date_Label {
            get {
                return ResourceManager.GetString("ItemDetailPage_Date_Label", resourceCulture);
            }
        }
        
        internal static string ItemDetailPage_Description_Label {
            get {
                return ResourceManager.GetString("ItemDetailPage_Description_Label", resourceCulture);
            }
        }
        
        internal static string ItemDetailPage_SuccessDialog_Title {
            get {
                return ResourceManager.GetString("ItemDetailPage_SuccessDialog_Title", resourceCulture);
            }
        }
        
        internal static string ItemDetailPage_SuccessDialog_AddedMessage {
            get {
                return ResourceManager.GetString("ItemDetailPage_SuccessDialog_AddedMessage", resourceCulture);
            }
        }
        
        internal static string ItemDetailPage_SuccessDialog_RemovedMessage {
            get {
                return ResourceManager.GetString("ItemDetailPage_SuccessDialog_RemovedMessage", resourceCulture);
            }
        }
        
        internal static string FavouritesPage_Title {
            get {
                return ResourceManager.GetString("FavouritesPage_Title", resourceCulture);
            }
        }
        
        internal static string FavouritesPage_List_Title {
            get {
                return ResourceManager.GetString("FavouritesPage_List_Title", resourceCulture);
            }
        }
        
        internal static string FavouritesPage_Empty_Label {
            get {
                return ResourceManager.GetString("FavouritesPage_Empty_Label", resourceCulture);
            }
        }
    }
}
